### ISSUE TITLE
Get parameter failed; Retrying in background

### ISSUE THREAD

**Issue by xorguy** [danielkaldheim/ha_airstage#2]
Hi.

I tried to install in my Home Assistant 2023.8.0 via local and I get error:
`Config entry 'local - xxxxxxxxxx' for fujitsu_airstage integration not ready yet: Get parameter failed; Retrying in background`

`Logger: homeassistant.config_entries
Source: config_entries.py:1250`

Tried with two different units and with same result.

**Comment by danielkaldheim** [comment]
Hi,

Thank you for letting me know. 

I assume you have the correct IP address for your unit. 

I'll add some more debugging information in the logs in the next update, so we can figure out which parameter failed.

If you want you could add this to configuration.yaml for more debug info:

```yml
logger:
  default: info
  logs:
    fujitsu_airstage: debug
    pyairstage: debug
```
