### ISSUE TITLE
Config-flow could not be loaded: 500 Internal server error

### ISSUE THREAD

**Issue by StevenHermans** [danielkaldheim/ha_airstage#29]
Hi Daniel,

I wanted to install the integration on my HA hosted on a docker container but I got the following issue.

`Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 12:16:57 (3 occurrences)
Last logged: 12:17:55

Unable to install package pyairstage>=1.1.1: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local' Check the permissions. [notice] A new release of pip is available: 23.2.1 -> 24.0 [notice] To update, run: pip install --upgrade pip`

Any idea how I can solve it? To which location is this ./local reference pointing?
I have the Airstage components available here: /home/pi/.../homeassistant/config/custom_components/fujitsu_airstage/
![image](https://github.com/danielkaldheim/ha_airstage/assets/43206923/a1d0a726-231b-4ac5-8eb8-170ff61d0f0d)

Can I also do a 'manual' installation adapting the .yaml files?

Tnx, Steven

**Comment by StevenHermans** [comment]
Found the solution by commenting out the User in the docker compose file in the home assistant section...Still wondering why this was required for the integration to work as other integrations worked perfectly without commenting out the user.

**Comment by danielkaldheim** [comment]
Would you care to share  your docker compose file @StevenHermans?

**Comment by ohshazbot** [comment]
This is the one I am using:

```
---
version: '3.3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/Media/docker/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    expose:
      - 8123
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" 
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```
